logging:
  level:
    root: INFO
server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/paymentdb
    username: root
    password: rootuser
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  # The eureka client config with config server.....
  config:
    import: configserver:http://localhost:9296
# The eureka client config without config server.....
#  eureka:
#    instance:
#      prefer-ip-address: true
#    client:
#      fetch-registry: true
#      register-with-eureka: true
#      service-url:
#        default-zone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka} #mention the IP:port of service registry
