spring:
  config:
    import: configserver:http://${CONFIG_SERVER_URL:localhost}:9296
  application:
    name: API-GATEWAY  # Name of the gateway service
  cloud:
    gateway:
      routes:
        - id: ORDER-SERVICE  # Identifier for the route
          predicates:
            - Path=/order/**  # Matches paths starting with "/microservice"
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
          uri: lb://ORDER-SERVICE  # Replace with the actual URI of your microservice
        - id: PAYMENT-SERVICE  # Identifier for the route
          predicates:
            - Path=/payment/**  # Matches paths starting with "/microservice"
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
          uri: lb://PAYMENT-SERVICE  #
        - id: PRODUCT-SERVICE  # Identifier for the route
          predicates:
            - Path=/product/**  # Matches paths starting with "/microservice"
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1 #how many requests per sec
                redis-rate-limiter.burstCapacity: 1
          uri: lb://PRODUCT-SERVICE
server:
  port: 9090  # Port on which the gateway will listen
okta:
  oauth2:
    issuer: https://dev-36646590.okta.com/oauth2/default
    audience: api://default
    client-id: 0oaeor99lkJamENKO5d7
    client-secret: v_jvEfHff3tzLCzm88whApBGKEF9hnGw9ie-_d8VR0JGsXTUwvYaqTT6G4NGMh9r
    scopes: internal, openid, profile, email, offline_access, address, phone, device_sso